jobs:
  - job: create_github_release
    steps:
      - task: GithubRelease@0
        inputs:
          action: create
          githubConnection: appiumbot
          repositoryName: appium/WebDriverAgent
          addChangeLog: false
  - template: ./templates/build.yml
    parameters:
      name: 'macOS_10_14'